# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Appium-UIAutomation' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Appium-UIAutomation
  pod 'TPKeyboardAvoiding'

  target 'Appium-UIAutomationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
